version: '3'
services:
    routes-map-ms:
        build: 
            dockerfile: Dockerfile
            context: .
        ports: 
            - "9090:9090"
        networks: 
            - network1
    routes-map-db:
        image: mongo
        ports:
          - "27016:27017"
        volumes:
          - "mongodata:/data/db"
        networks:
          - network1

volumes:
    mongodata:
networks:
    network1: